version: "3"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_debug
    ports:
      - "9000:9000"
    depends_on:
      db-mysql-5.7:
        condition: service_healthy
    networks:
      - test
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/target/database-manager-0.0.1-SNAPSHOT.jar

  db-mysql-5.7:
    image: opavlova/db-mysql:5.7-test
    container_name: db-mysql-5.7
    ports:
      - "13306:3306"
    healthcheck:
          test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
          interval: 1s
          timeout: 3s
          retries: 30
    networks:
      - test
