version: '3'

services:
  test-oracle-compose:
    image: deepdiver/docker-oracle-xe-11g
    environment:
      ORACLE_MEM: 1000
    ports:
      - "11521:1521"
    networks:
      - oracle-compose-network

networks:
  oracle-compose-network:
    driver: bridge