version: '3'

services:
  test-oracle-compose:
    image: deepdiver/docker-oracle-xe-11g
    ports:
      - "11521:1521"
    volumes:
      - /Users/hsseo/docker/oracle/oradata:/opt/oracle/oradata
    networks:
      - oracle-compose-network

networks:
  oracle-compose-network:
    driver: bridge